---
title: "Linear Regression"
output: html_document
---


```{r}
library(dplyr)
library(tidyverse)
library(rsample)
library(purrr)
library(broom)
library(modelr)
library(mgcv)
library(MASS)
```

```{r}
collision_df = read.csv("data/collision_df.csv")
```


```{r}
collision_cleaned_df <- collision_df |>
  drop_na(num_casualty, hour, day_of_week, latitude, longitude, vehicle_year) |>
  mutate(
    num_casualty = as.numeric(num_casualty),
    vehicle_year = as.numeric(vehicle_year)
  ) |>
  filter(vehicle_year > 1950 & vehicle_year <= year) |>
  mutate(day_of_week = factor(day_of_week, 
                         levels = c("Sunday", "Monday", "Tuesday", "Wednesday", 
                                    "Thursday", "Friday", "Saturday")),
    num_casualty = as.numeric(num_casualty),
    vehicle_year = as.numeric(vehicle_year),
    hour_factor = as.factor(hour)
  ) |>mutate(
    sqrt_casualty = sqrt(num_casualty + 1)
  )
  
```


```{r}
glm_nb_fit_A <- glm.nb(num_casualty ~ hour_factor + day_of_week + latitude + longitude + vehicle_year, data = collision_cleaned_df)

```

```{r}
broom::tidy(glm_nb_fit_A, conf.int = TRUE, exponentiate = TRUE) |> 
  knitr::kable()
  
```



```{r}
models_to_compare <- list(
  model_A_main = num_casualty ~ hour_factor + day_of_week + latitude + longitude + vehicle_year,
  model_B_interact = num_casualty ~ hour_factor * day_of_week + latitude + longitude + vehicle_year,
  model_C_control = num_casualty ~ latitude + longitude + vehicle_year 
)
```


```{r}
cv_data <- crossv_mc(collision_cleaned_df, n = 100, test = 0.20)
```

```{r}
cv_results <- cv_data |>
  mutate(model_form = list(models_to_compare)) |>
  unnest(model_form) |>
  mutate(
    fit = map2(model_form, train, 
               ~MASS::glm.nb(.x, data = as_tibble(.y))
    )
  )
```



```{r}
final_comparison_summary <- cv_results |>
  group_by(model_form) |>
  summarize(
    Mean_CV_RMSE = mean(rmse),
    Std_Error = sd(rmse) / sqrt(n()),
    .groups = 'drop'
  ) |>
  arrange(Mean_CV_RMSE)
```





