---
title: "data_import"
author: "Liliang Su"
date: "2025-11-03"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```


crash
```{r}
crash_df = read_csv("./data/Motor_Vehicle_Collisions_-_Crashes_20251104.csv", na = c("NA",".","")) |>
  janitor::clean_names() |> 
  
  # Keep only Manhattan records
  filter(borough == "MANHATTAN") |>
  
  # Separate the crash_date column (creates character columns)
  separate(
    crash_date,
    into = c("month", "day", "year"),
    sep = "/"
  ) |>
  
  # filter for the specified range (2021-2025)
  mutate(year = as.numeric(year),
         month = as.numeric(month),
         day = as.numeric(day)) |>
  filter(year %in% 2021:2025)  |> 
  # keep data up to October 31, 2025. 
  filter(
    !(year == 2025 & month == 11 & day %in% c(1, 2))
  ) |>

  relocate(year, month, day, crash_time, collision_id)

write_csv(crash_df, "./data/crash_20251031_filtered.csv")
```

vehicle
```{r}
vehicle_df = read_csv("./data/Motor_Vehicle_Collisions_-_Vehicles_20251104.csv", na = c("NA",".","")) |>
  janitor::clean_names() |> 
  semi_join(crash_df, by = "collision_id")

write_csv(vehicle_df, "./data/vehicle_20251031_filtered.csv")

```

person
```{r}
person_df = read_csv("./data/Motor_Vehicle_Collisions_-_Person_20251104.csv", na = c("NA",".","")) |>
  janitor::clean_names() |> 
  semi_join(crash_df, by = "collision_id")

write_csv(person_df, "./data/person_20251031_filtered.csv")

```
